package com.yyf.mallcache.mapper;


import com.yyf.mallcache.bean.Car;

import java.util.List;

public interface CarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_car
     *
     * @mbggenerated Fri Aug 02 11:29:41 CST 2019
     */
    int deleteByPrimaryKey(Integer carId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_car
     *
     * @mbggenerated Fri Aug 02 11:29:41 CST 2019
     */
    int insert(Car record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_car
     *
     * @mbggenerated Fri Aug 02 11:29:41 CST 2019
     */
    Car selectByPrimaryKey(Integer carId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_car
     *
     * @mbggenerated Fri Aug 02 11:29:41 CST 2019
     */
    List<Car> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_car
     *
     * @mbggenerated Fri Aug 02 11:29:41 CST 2019
     */
    int updateByPrimaryKey(Car record);
}