package com.yyf.mallcache.mapper;




import com.yyf.mallcache.bean.Image;
import org.apache.ibatis.annotations.Param;
import org.springframework.cache.annotation.Cacheable;

import java.util.List;

public interface ImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_image
     *
     * @mbggenerated Sat Jul 27 15:21:00 CST 2019
     */
    int deleteByPrimaryKey(Integer imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_image
     *
     * @mbggenerated Sat Jul 27 15:21:00 CST 2019
     */
    int insert(Image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_image
     *
     * @mbggenerated Sat Jul 27 15:21:00 CST 2019
     */
    Image selectByPrimaryKey(Integer imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_image
     *
     * @mbggenerated Sat Jul 27 15:21:00 CST 2019
     */
    List<Image> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_image
     *
     * @mbggenerated Sat Jul 27 15:21:00 CST 2019
     */
    int updateByPrimaryKey(Image record);
    /**ͨ����ƷID��ѯ�������Ϊ��ѯ��ͼƬ
     * 
     * @return
     */
    Image selectByProductIdGetSearchImage(Integer productId);
    
    List<Image> selectByProductIdGetKindImage(@Param("productId") Integer productId, @Param("imageKind") String imageKind);
    
    Image selectByProductIdGetCartImage(Integer productId);
}