package com.yyf.mallcache.mapper;

import com.yyf.mallcache.bean.Order;
import java.util.List;

import com.yyf.mallcache.bean.Product;
import org.apache.ibatis.annotations.Param;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.CachePut;
import org.springframework.cache.annotation.Cacheable;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbggenerated Sat Jul 27 15:21:00 CST 2019
     */
    @CacheEvict(cacheNames ={"productId"})
    int deleteByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbggenerated Sat Jul 27 15:21:00 CST 2019
     */
    Integer insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbggenerated Sat Jul 27 15:21:00 CST 2019
     */
    @Cacheable(cacheNames ={"productId"} )
    Product selectByPrimaryKey(Integer productId);

   /**
    * ͨ��������ҳ��ʾ
    * @return
    */
   @Cacheable(cacheNames ={"condition"} )
    List<Product> selectPageByCondition(@Param("pageNo") Integer pageNo, @Param("pageSize") Integer pageSize
           , @Param("productKind") String productKind, @Param("orderWay") Integer orderWay, @Param("productName") String productName);
    Integer getTotalcountByCondition(@Param("productKind") String productKind
            , @Param("productName") String productName);
/*
通过用户id 查询其上架商品
 */
    List<Product> selectProductByUserId( @Param("userId") Integer userId);

    int updateByPrimaryKey(Product record);
    
    List<String> selectTasteByProductName(String productName);
    
    Product getCartProductByPrimaryKey(Integer productId);
  
}