package com.yyf.mallcache.mapper;


import com.yyf.mallcache.bean.SecProduct;

import java.util.List;

public interface SecProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_product
     *
     * @mbggenerated Sun Aug 18 18:55:30 CST 2019
     */
    int deleteByPrimaryKey(Integer secproductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_product
     *
     * @mbggenerated Sun Aug 18 18:55:30 CST 2019
     */
    int insert(SecProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_product
     *
     * @mbggenerated Sun Aug 18 18:55:30 CST 2019
     */
   

 
    List<SecProduct> selectAll();

  
    int updateByPrimaryKey(SecProduct record);
    
    int updateStoreNumberAndSaleAmountById(Integer secproductId);
    
    SecProduct selectByPrimaryKey(Integer secproductId);
    
    SecProduct selectByProductId(Integer productId);
    /**
               * ���ҿ��
     * @return
     */
    Integer selectStoreNumberById(Integer secproductId);
    
   
}