package com.yyf.mallcache.mapper;


import java.util.List;

import com.yyf.mallcache.bean.ShoppingItem;
import org.apache.ibatis.annotations.Param;

public interface ShoppingItemMapper {
/**
 * ͨ���û�idɾ��������
 * @param itemId
 * @return
 */
    int deleteByUserId(Integer userId);

 
    int insert(ShoppingItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_item
     *
     * @mbggenerated Tue Jul 30 09:42:32 CST 2019
     */
    ShoppingItem selectByPrimaryKey(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_item
     *
     * @mbggenerated Tue Jul 30 09:42:32 CST 2019
     */
    List<ShoppingItem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_item
     *
     * @mbggenerated Tue Jul 30 09:42:32 CST 2019
     */
    int updateByUserIdAndProductId(ShoppingItem record);
    //ͨ���û�id�Ͳ�Ʒidɾ��
    int deleteByUserIdAndProductIdy(@Param("productId") Integer productId, @Param("userId") Integer userId);
    //ͨ���û�id��ѯ���е���Ʒ��
    List<ShoppingItem> selectByUserId(Integer usetId);
    //ͨ���û�id���Ʒid��ѯ ��Ʒ����
    Integer selectByUserIdAndProductId(@Param("productId") Integer productId, @Param("userId") Integer userId);
   /**
    * ͨ���û�id���Ʒid��� ��Ʒ��
    * @param productId
    * @param userId
    * @return
    */
    ShoppingItem getItemByProductIdAndUserId(@Param("productId") Integer productId, @Param("userId") Integer userId);
}