package com.yyf.mallcache.bean;

import java.io.Serializable;

public class Image implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_image.image_id
     *
     * @mbggenerated Sat Jul 27 15:21:00 CST 2019
     */
    private Integer imageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_image.image_name
     *
     * @mbggenerated Sat Jul 27 15:21:00 CST 2019
     */
    private String imageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_image.image_path
     *
     * @mbggenerated Sat Jul 27 15:21:00 CST 2019
     */
    private String imagePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_image.image_id
     *
     * @return the value of mall_image.image_id
     *
     * @mbggenerated Sat Jul 27 15:21:00 CST 2019
     */
    public Integer getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_image.image_id
     *
     * @param imageId the value for mall_image.image_id
     *
     * @mbggenerated Sat Jul 27 15:21:00 CST 2019
     */
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_image.image_name
     *
     * @return the value of mall_image.image_name
     *
     * @mbggenerated Sat Jul 27 15:21:00 CST 2019
     */
    public String getImageName() {
        return imageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_image.image_name
     *
     * @param imageName the value for mall_image.image_name
     *
     * @mbggenerated Sat Jul 27 15:21:00 CST 2019
     */
    public void setImageName(String imageName) {
        this.imageName = imageName == null ? null : imageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_image.image_path
     *
     * @return the value of mall_image.image_path
     *
     * @mbggenerated Sat Jul 27 15:21:00 CST 2019
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_image.image_path
     *
     * @param imagePath the value for mall_image.image_path
     *
     * @mbggenerated Sat Jul 27 15:21:00 CST 2019
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath == null ? null : imagePath.trim();
    }

	@Override
	public String toString() {
		return "Image [imageId=" + imageId + ", imageName=" + imageName + ", imagePath=" + imagePath + "]";
	}
    
}